apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: centsideas-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - localhost
        - serach.localhost
  rules:
    - host: search.localhost
      http:
        paths:
          - backend:
              serviceName: search
              servicePort: 3333
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: search
              servicePort: 3333
